"""Add reporter_id to incidents table

Revision ID: 244cc4f41630
Revises: 9544e2c91326
Create Date: 2025-07-21 12:20:50.641306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244cc4f41630'
down_revision = '9544e2c91326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('incidents_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['reporter_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('incidents_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('reporter_id')

    # ### end Alembic commands ###
